// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ZN1FaMjvl2SfQgiHDwpBjI6MbupThcQ',
    appId: '1:617643061997:web:058d6715bc144d2ab452e4',
    messagingSenderId: '617643061997',
    projectId: 'chatter-a-39bd4',
    authDomain: 'chatter-a-39bd4.firebaseapp.com',
    storageBucket: 'chatter-a-39bd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaLwPZtjhaaX8bXz4NNC480GUVuZQtMo',
    appId: '1:617643061997:android:fd0ab27ef25bc82cb452e4',
    messagingSenderId: '617643061997',
    projectId: 'chatter-a-39bd4',
    storageBucket: 'chatter-a-39bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbID_U4Qj5vTWWBaeu-B_Pcq4Mba40Xl8',
    appId: '1:617643061997:ios:f8147e681fe11903b452e4',
    messagingSenderId: '617643061997',
    projectId: 'chatter-a-39bd4',
    storageBucket: 'chatter-a-39bd4.appspot.com',
    iosClientId: '617643061997-4pgg16js0mfc652j6bb6ct6c5gn6uvav.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbID_U4Qj5vTWWBaeu-B_Pcq4Mba40Xl8',
    appId: '1:617643061997:ios:f8147e681fe11903b452e4',
    messagingSenderId: '617643061997',
    projectId: 'chatter-a-39bd4',
    storageBucket: 'chatter-a-39bd4.appspot.com',
    iosClientId: '617643061997-4pgg16js0mfc652j6bb6ct6c5gn6uvav.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );
}
